# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img_popout.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_img_popout(object):
    def setupUi(self, img_popout):
        img_popout.setObjectName("img_popout")
        img_popout.resize(589, 488)
        self.gridLayout = QtWidgets.QGridLayout(img_popout)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(img_popout)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(img_popout)
        QtCore.QMetaObject.connectSlotsByName(img_popout)

    def retranslateUi(self, img_popout):
        _translate = QtCore.QCoreApplication.translate
        img_popout.setWindowTitle(_translate("img_popout", "WARNING"))
        self.label.setText(_translate("img_popout", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    img_popout = QtWidgets.QWidget()
    ui = Ui_img_popout()
    ui.setupUi(img_popout)
    img_popout.show()
    sys.exit(app.exec_())
