# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_maintenance_karma.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        Form.move(400,50)
        Form.setMinimumSize(QtCore.QSize(1280, 800))
        Form.setMaximumSize(QtCore.QSize(1280, 800))
        Form.setStyleSheet("")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(170, 60, 931, 721))
        self.label_6.setStyleSheet("")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/maintenance_karma.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 1, 1211, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.layoutWidget_3 = QtWidgets.QWidget(Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 60, 121, 148))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_20.setMinimumSize(QtCore.QSize(119, 35))
        self.label_20.setMaximumSize(QtCore.QSize(119, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_6.addWidget(self.label_20)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_16.addWidget(self.label_19)
        self.label_clamp_1 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_clamp_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_clamp_1.setText("")
        self.label_clamp_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_clamp_1.setScaledContents(True)
        self.label_clamp_1.setObjectName("label_clamp_1")
        self.horizontalLayout_16.addWidget(self.label_clamp_1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.label_switch1_1 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_switch1_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch1_1.setText("")
        self.label_switch1_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch1_1.setScaledContents(True)
        self.label_switch1_1.setObjectName("label_switch1_1")
        self.horizontalLayout_18.addWidget(self.label_switch1_1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.label_switch2_1 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_switch2_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch2_1.setText("")
        self.label_switch2_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch2_1.setScaledContents(True)
        self.label_switch2_1.setObjectName("label_switch2_1")
        self.horizontalLayout_19.addWidget(self.label_switch2_1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.layoutWidget_4 = QtWidgets.QWidget(Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 250, 121, 148))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_24.setMinimumSize(QtCore.QSize(119, 35))
        self.label_24.setMaximumSize(QtCore.QSize(119, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_20.addWidget(self.label_25)
        self.label_clamp_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_clamp_2.setMaximumSize(QtCore.QSize(20, 20))
        self.label_clamp_2.setText("")
        self.label_clamp_2.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_clamp_2.setScaledContents(True)
        self.label_clamp_2.setObjectName("label_clamp_2")
        self.horizontalLayout_20.addWidget(self.label_clamp_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_22.addWidget(self.label_27)
        self.label_switch1_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_switch1_2.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch1_2.setText("")
        self.label_switch1_2.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch1_2.setScaledContents(True)
        self.label_switch1_2.setObjectName("label_switch1_2")
        self.horizontalLayout_22.addWidget(self.label_switch1_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        self.label_switch2_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_switch2_2.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch2_2.setText("")
        self.label_switch2_2.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch2_2.setScaledContents(True)
        self.label_switch2_2.setObjectName("label_switch2_2")
        self.horizontalLayout_23.addWidget(self.label_switch2_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.layoutWidget_5 = QtWidgets.QWidget(Form)
        self.layoutWidget_5.setGeometry(QtCore.QRect(30, 440, 125, 148))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_29.setMinimumSize(QtCore.QSize(119, 35))
        self.label_29.setMaximumSize(QtCore.QSize(119, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_8.addWidget(self.label_29)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_24.addWidget(self.label_30)
        self.label_clamp_3 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_clamp_3.setMaximumSize(QtCore.QSize(20, 20))
        self.label_clamp_3.setText("")
        self.label_clamp_3.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_clamp_3.setScaledContents(True)
        self.label_clamp_3.setObjectName("label_clamp_3")
        self.horizontalLayout_24.addWidget(self.label_clamp_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_26.addWidget(self.label_32)
        self.label_switch1_3 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_switch1_3.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch1_3.setText("")
        self.label_switch1_3.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch1_3.setScaledContents(True)
        self.label_switch1_3.setObjectName("label_switch1_3")
        self.horizontalLayout_26.addWidget(self.label_switch1_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_27.addWidget(self.label_33)
        self.label_switch2_3 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_switch2_3.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch2_3.setText("")
        self.label_switch2_3.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch2_3.setScaledContents(True)
        self.label_switch2_3.setObjectName("label_switch2_3")
        self.horizontalLayout_27.addWidget(self.label_switch2_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.layoutWidget_6 = QtWidgets.QWidget(Form)
        self.layoutWidget_6.setGeometry(QtCore.QRect(30, 630, 125, 148))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_34.setMinimumSize(QtCore.QSize(119, 35))
        self.label_34.setMaximumSize(QtCore.QSize(119, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_9.addWidget(self.label_34)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_28.addWidget(self.label_35)
        self.label_clamp_4 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_clamp_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_clamp_4.setText("")
        self.label_clamp_4.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_clamp_4.setScaledContents(True)
        self.label_clamp_4.setObjectName("label_clamp_4")
        self.horizontalLayout_28.addWidget(self.label_clamp_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_30.addWidget(self.label_37)
        self.label_switch1_4 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_switch1_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch1_4.setText("")
        self.label_switch1_4.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch1_4.setScaledContents(True)
        self.label_switch1_4.setObjectName("label_switch1_4")
        self.horizontalLayout_30.addWidget(self.label_switch1_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_31.addWidget(self.label_38)
        self.label_switch2_4 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_switch2_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch2_4.setText("")
        self.label_switch2_4.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch2_4.setScaledContents(True)
        self.label_switch2_4.setObjectName("label_switch2_4")
        self.horizontalLayout_31.addWidget(self.label_switch2_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_31)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(970, 70, 162, 87))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setWordWrap(True)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_3.addWidget(self.label_51)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.spinBox_encoder = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_encoder.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_encoder.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_encoder.setMaximum(999999)
        self.spinBox_encoder.setObjectName("spinBox_encoder")
        self.horizontalLayout_2.addWidget(self.spinBox_encoder)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_2.setMaximum(2457)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout_3.addWidget(self.horizontalSlider_2)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(350, 380, 91, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_50 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_50.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_50.setScaledContents(False)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setWordWrap(True)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout.addWidget(self.label_50)
        self.label_light = QtWidgets.QLabel(self.layoutWidget1)
        self.label_light.setMaximumSize(QtCore.QSize(20, 20))
        self.label_light.setText("")
        self.label_light.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_light.setScaledContents(True)
        self.label_light.setObjectName("label_light")
        self.horizontalLayout.addWidget(self.label_light)
        self.label_39 = QtWidgets.QLabel(Form)
        self.label_39.setGeometry(QtCore.QRect(740, 430, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap(":/icons/number_four_navigate_menu_options-512.png"))
        self.label_39.setScaledContents(True)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(Form)
        self.label_40.setGeometry(QtCore.QRect(620, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_40.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap(":/icons/number_three_navigate_menu_options-512.png"))
        self.label_40.setScaledContents(True)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setWordWrap(True)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setGeometry(QtCore.QRect(470, 500, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_41.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap(":/icons/number_two_navigate_menu_options-512.png"))
        self.label_41.setScaledContents(True)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setGeometry(QtCore.QRect(320, 520, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap(":/icons/number_one_navigate_menu_options-2-512.png"))
        self.label_42.setScaledContents(True)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(Form)
        self.label_43.setGeometry(QtCore.QRect(1000, 510, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_43.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_43.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap(":/icons/number_five_navigate_menu_options-512.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(Form)
        self.label_44.setGeometry(QtCore.QRect(0, 40, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_44.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap(":/icons/number_one_navigate_menu_options-2-512.png"))
        self.label_44.setScaledContents(True)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(Form)
        self.label_45.setGeometry(QtCore.QRect(0, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_45.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap(":/icons/number_two_navigate_menu_options-512.png"))
        self.label_45.setScaledContents(True)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setWordWrap(True)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(Form)
        self.label_46.setGeometry(QtCore.QRect(0, 420, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap(":/icons/number_three_navigate_menu_options-512.png"))
        self.label_46.setScaledContents(True)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setWordWrap(True)
        self.label_46.setObjectName("label_46")
        self.label_52 = QtWidgets.QLabel(Form)
        self.label_52.setGeometry(QtCore.QRect(0, 610, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_52.setText("")
        self.label_52.setPixmap(QtGui.QPixmap(":/icons/number_four_navigate_menu_options-512.png"))
        self.label_52.setScaledContents(True)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setWordWrap(True)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(Form)
        self.label_53.setGeometry(QtCore.QRect(1100, 460, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.5 rgba(200, 200, 200, 200), stop:1 rgba(200, 200, 200, 200));")
        self.label_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_53.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap(":/icons/number_five_navigate_menu_options-512.png"))
        self.label_53.setScaledContents(True)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(1110, 500, 151, 102))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_54.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_54.setWordWrap(True)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_3.addWidget(self.label_54)
        self.label_pushbutton = QtWidgets.QLabel(self.layoutWidget2)
        self.label_pushbutton.setMaximumSize(QtCore.QSize(20, 20))
        self.label_pushbutton.setText("")
        self.label_pushbutton.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_pushbutton.setScaledContents(True)
        self.label_pushbutton.setObjectName("label_pushbutton")
        self.horizontalLayout_3.addWidget(self.label_pushbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_56 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_56.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_56.setWordWrap(True)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_4.addWidget(self.label_56)
        self.label_reset_switch = QtWidgets.QLabel(self.layoutWidget2)
        self.label_reset_switch.setMaximumSize(QtCore.QSize(20, 20))
        self.label_reset_switch.setText("")
        self.label_reset_switch.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_reset_switch.setScaledContents(True)
        self.label_reset_switch.setObjectName("label_reset_switch")
        self.horizontalLayout_4.addWidget(self.label_reset_switch)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_55 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_55.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_5.addWidget(self.label_55)
        self.label_eStop = QtWidgets.QLabel(self.layoutWidget2)
        self.label_eStop.setMaximumSize(QtCore.QSize(20, 20))
        self.label_eStop.setText("")
        self.label_eStop.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_eStop.setScaledContents(True)
        self.label_eStop.setObjectName("label_eStop")
        self.horizontalLayout_5.addWidget(self.label_eStop)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.label_clamp_1_2 = QtWidgets.QLabel(Form)
        self.label_clamp_1_2.setGeometry(QtCore.QRect(348, 446, 10, 10))
        self.label_clamp_1_2.setMaximumSize(QtCore.QSize(20, 20))
        self.label_clamp_1_2.setText("")
        self.label_clamp_1_2.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_clamp_1_2.setScaledContents(True)
        self.label_clamp_1_2.setObjectName("label_clamp_1_2")
        self.label_switch1_1_1 = QtWidgets.QLabel(Form)
        self.label_switch1_1_1.setGeometry(QtCore.QRect(310, 440, 10, 10))
        self.label_switch1_1_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch1_1_1.setText("")
        self.label_switch1_1_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch1_1_1.setScaledContents(True)
        self.label_switch1_1_1.setObjectName("label_switch1_1_1")
        self.label_switch2_1_1 = QtWidgets.QLabel(Form)
        self.label_switch2_1_1.setGeometry(QtCore.QRect(390, 460, 10, 10))
        self.label_switch2_1_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch2_1_1.setText("")
        self.label_switch2_1_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch2_1_1.setScaledContents(True)
        self.label_switch2_1_1.setObjectName("label_switch2_1_1")
        self.label_clamp_2_1 = QtWidgets.QLabel(Form)
        self.label_clamp_2_1.setGeometry(QtCore.QRect(480, 450, 10, 10))
        self.label_clamp_2_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_clamp_2_1.setText("")
        self.label_clamp_2_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_clamp_2_1.setScaledContents(True)
        self.label_clamp_2_1.setObjectName("label_clamp_2_1")
        self.label_switch1_2_1 = QtWidgets.QLabel(Form)
        self.label_switch1_2_1.setGeometry(QtCore.QRect(450, 450, 10, 10))
        self.label_switch1_2_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch1_2_1.setText("")
        self.label_switch1_2_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch1_2_1.setScaledContents(True)
        self.label_switch1_2_1.setObjectName("label_switch1_2_1")
        self.label_switch2_2_1 = QtWidgets.QLabel(Form)
        self.label_switch2_2_1.setGeometry(QtCore.QRect(500, 440, 10, 10))
        self.label_switch2_2_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch2_2_1.setText("")
        self.label_switch2_2_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch2_2_1.setScaledContents(True)
        self.label_switch2_2_1.setObjectName("label_switch2_2_1")
        self.label_switch1_3_1 = QtWidgets.QLabel(Form)
        self.label_switch1_3_1.setGeometry(QtCore.QRect(676, 398, 10, 10))
        self.label_switch1_3_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch1_3_1.setText("")
        self.label_switch1_3_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch1_3_1.setScaledContents(True)
        self.label_switch1_3_1.setObjectName("label_switch1_3_1")
        self.label_switch2_3_1 = QtWidgets.QLabel(Form)
        self.label_switch2_3_1.setGeometry(QtCore.QRect(640, 350, 10, 10))
        self.label_switch2_3_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch2_3_1.setText("")
        self.label_switch2_3_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch2_3_1.setScaledContents(True)
        self.label_switch2_3_1.setObjectName("label_switch2_3_1")
        self.label_switch1_4_1 = QtWidgets.QLabel(Form)
        self.label_switch1_4_1.setGeometry(QtCore.QRect(740, 394, 10, 10))
        self.label_switch1_4_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch1_4_1.setText("")
        self.label_switch1_4_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch1_4_1.setScaledContents(True)
        self.label_switch1_4_1.setObjectName("label_switch1_4_1")
        self.label_switch2_4_1 = QtWidgets.QLabel(Form)
        self.label_switch2_4_1.setGeometry(QtCore.QRect(800, 403, 10, 10))
        self.label_switch2_4_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_switch2_4_1.setText("")
        self.label_switch2_4_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_switch2_4_1.setScaledContents(True)
        self.label_switch2_4_1.setObjectName("label_switch2_4_1")
        self.label_pushbutton_1 = QtWidgets.QLabel(Form)
        self.label_pushbutton_1.setGeometry(QtCore.QRect(1003, 479, 10, 10))
        self.label_pushbutton_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_pushbutton_1.setText("")
        self.label_pushbutton_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_pushbutton_1.setScaledContents(True)
        self.label_pushbutton_1.setObjectName("label_pushbutton_1")
        self.label_reset_switch_1 = QtWidgets.QLabel(Form)
        self.label_reset_switch_1.setGeometry(QtCore.QRect(1026, 476, 10, 10))
        self.label_reset_switch_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_reset_switch_1.setText("")
        self.label_reset_switch_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_reset_switch_1.setScaledContents(True)
        self.label_reset_switch_1.setObjectName("label_reset_switch_1")
        self.label_clamp_3_1 = QtWidgets.QLabel(Form)
        self.label_clamp_3_1.setGeometry(QtCore.QRect(655, 375, 10, 10))
        self.label_clamp_3_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_clamp_3_1.setText("")
        self.label_clamp_3_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_clamp_3_1.setScaledContents(True)
        self.label_clamp_3_1.setObjectName("label_clamp_3_1")
        self.label_clamp_4_1 = QtWidgets.QLabel(Form)
        self.label_clamp_4_1.setGeometry(QtCore.QRect(760, 410, 10, 10))
        self.label_clamp_4_1.setMaximumSize(QtCore.QSize(20, 20))
        self.label_clamp_4_1.setText("")
        self.label_clamp_4_1.setPixmap(QtGui.QPixmap(":/icons/iconfinder_Circle_Grey_34212.png"))
        self.label_clamp_4_1.setScaledContents(True)
        self.label_clamp_4_1.setObjectName("label_clamp_4_1")
        self.label_6.raise_()
        self.label_53.raise_()
        self.label_52.raise_()
        self.label_46.raise_()
        self.label_45.raise_()
        self.label_44.raise_()
        self.label_12.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_4.raise_()
        self.layoutWidget_5.raise_()
        self.layoutWidget_6.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.layoutWidget.raise_()
        self.label_clamp_1_2.raise_()
        self.label_switch1_1_1.raise_()
        self.label_switch2_1_1.raise_()
        self.label_clamp_2_1.raise_()
        self.label_switch1_2_1.raise_()
        self.label_switch2_2_1.raise_()
        self.label_switch1_3_1.raise_()
        self.label_switch2_3_1.raise_()
        self.label_switch1_4_1.raise_()
        self.label_switch2_4_1.raise_()
        self.label_pushbutton_1.raise_()
        self.label_reset_switch_1.raise_()
        self.label_clamp_3_1.raise_()
        self.label_clamp_4_1.raise_()

        self.retranslateUi(Form)
        self.spinBox_encoder.valueChanged['int'].connect(self.horizontalSlider_2.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_12.setText(_translate("Form", "Karma Station"))
        self.label_20.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">FuseBox Vision</span></p></body></html>"))
        self.label_19.setText(_translate("Form", "Clamp"))
        self.label_22.setText(_translate("Form", "Switch 1"))
        self.label_23.setText(_translate("Form", "Switch 2"))
        self.label_24.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">181967 Vision</span></p></body></html>"))
        self.label_25.setText(_translate("Form", "Clamp"))
        self.label_27.setText(_translate("Form", "Switch 1"))
        self.label_28.setText(_translate("Form", "Switch 2"))
        self.label_29.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">FuseBox Torque</span></p></body></html>"))
        self.label_30.setText(_translate("Form", "Clamp"))
        self.label_32.setText(_translate("Form", "Switch 1"))
        self.label_33.setText(_translate("Form", "Switch 2"))
        self.label_34.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">181967 Torque</span></p></body></html>"))
        self.label_35.setText(_translate("Form", "Clamp"))
        self.label_37.setText(_translate("Form", "Switch 1"))
        self.label_38.setText(_translate("Form", "Switch 2"))
        self.label_51.setText(_translate("Form", "Encoder 1"))
        self.label_50.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Light</p></body></html>"))
        self.label_54.setText(_translate("Form", "PushButton"))
        self.label_56.setText(_translate("Form", "ResetSwitch"))
        self.label_55.setText(_translate("Form", "EStop"))


if __name__ == "__main__":
    import icons_rc
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec_())
